### ISSUE TITLE
Allow bypass of super user check for certain roles ?

### ISSUE THREAD

**Issue by adarshkoyya** [dimitri/pgextwlist#25]
Hi, 
I have used this plugin and it works well. But the problem is any user can create create or drop extensions, which i want to avoid. 

Instead I want to create a role called extension_admin in postgress and only this user should be able to bypass the superuser check rest should still be not able to create or drop extension. 

Is this possible if yes then how ?

**Comment by adarshkoyya** [comment]
@dimitri @Peeja  Could you please help me out here.

**Comment by dimitri** [comment]
What would then be the difference in between this `extension_admin` role and superuser? Other than that the extension was scheduled to be obsoleted by `pginstall` so any new development would happen there.

**Comment by chobostar** [comment]
@adarshkoyya 

It possible to do it with:
```
alter user extension_admin set session_preload_libraries = 'pgextwlist';
```
and disable it by default it `postgresql.conf`

but keep in my that any user can atler themself with `local_preload_libraries = 'pgextwlist'` and skip restrict.

**Comment by jankatins** [comment]
We use pgextwlist to grant extension creation/update capabilities to customers without giving them superuser rights. For us it would be nice to be able to give our customers the ability to only have "some" users being able to change extensions instead of all users being able to do this.

superuser -> customer "pseudo-superuser" which can install/change extensions -> customer "normal user" without such rights

Would you be open to a patch which implements this?
